cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
credentials:
  usernames:
    admin:
      email: admin2@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Mateus
      password: $2b$12$uhf1afrDxOORi1PXmTnpXO.Uc2R4TMbjMWRku4RcouJDA0OOuhakO
    jony:
      email: mateusalbano22222222222222@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Mateus Lopes Albano
      password: $2b$12$4WTS4J7WQiLj1oQfoEZomOS0Dh8EAlwAzgMmHWKEQeARa3Ynb.AX.
    mateus:
      email: admin2@admin.com
      failed_login_attempts: 0
      logged_in: false
      name: Mateus
      password: $2b$12$hR6Y1krttRPOx8WALPZVOemQYU3WheNUfohRurT6/sthZ5I1PL6Ja
    professor:
      email: heloisalopesalbano@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: 'Heydrian '
      password: $2b$12$v6pWRLx.gdSfmG8YgI2gIurDy.CGCWs5zyvJAMx1GgxWH0xJQr2Gy
preauthorized:
  emails:
  - admin@gmail.com
