version: '3.8'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - nestnet
  db:
    image: postgres:latest
    restart: always
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=db
    networks:
      - nestnet

networks:
  nestnet:
    driver: bridge